### ISSUE TITLE
Service实例变量名最后的Impl是必须的吗？

### ISSUE THREAD

**Issue by daanhan** [davidfantasy/mybatis-plus-generator-ui#24]
### 当前使用版本(必填,否则不予处理)
当前最新版本 1.2.2
### 该问题是如何引起的？(确定最新版也有问题再提!!!)
最新版本也有问题。
采用默认模板，连接oracle数据库，生成表user_info相关的代码。
使用UserInfoService时，如果实例变量名为xxxService则报错
> @Resource
UserInfoService userInfoService;// 报错

`Caused by: org.apache.ibatis.binding.BindingException: Invalid bound statement (not found): xxx.yyy.zzz.service.UserInfoService.getBaseMapper
`

如果变量实例名为xxxServiceImpl，则正常不报错。
> @Resource
UserInfoService userInfoServiceImpl;

### 重现步骤(如果有就写完整)
仅仅变量实例名称的差异，为什么呢？
### 报错信息
> Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
09:46:29.781 logback [main] ERROR o.s.boot.SpringApplication - Application run failed
java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:798)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:779)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at xxx.yyy.zzz.App.main(App.java:11)
Caused by: org.apache.ibatis.binding.BindingException: Invalid bound statement (not found): xxx.yyy.zzz.service.UserInfoService.getBaseMapper
	at org.apache.ibatis.binding.MapperMethod$SqlCommand.<init>(MapperMethod.java:235)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.<init>(MybatisMapperMethod.java:50)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.lambda$cachedMapperMethod$0(MybatisMapperProxy.java:101)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy$$Lambda$406/1831705084.apply(Unknown Source)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.cachedMapperMethod(MybatisMapperProxy.java:100)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:95)
	at com.sun.proxy.$Proxy50.getBaseMapper(Unknown Source)
	at com.baomidou.mybatisplus.extension.service.IService.list(IService.java:275)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:625)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invokeDefaultMethodJava8(MybatisMapperProxy.java:117)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:87)
	at com.sun.proxy.$Proxy50.list(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:205)
	at com.sun.proxy.$Proxy51.list(Unknown Source)
	at xxx.yyy.zzz.TestApp.testSelect(TestApp.java:44)
	at xxx.yyy.zzz.TestApp.run(TestApp.java:49)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:795)

**Comment by davidfantasy** [comment]
仅仅是变量名的差异应该是不会有任何影响的，你需要看一下报错的情况下，是不是确实生成了ServiceImpl的类。正确生成的代码类似这样，你可以对照看一下
~~~java
/**
 * 服务接口类
 */
public interface UserService extends IService<User> {

}
~~~
~~~java
/**
 * 服务实现类
 */
@Service
public class UserServiceImpl extends ServiceImpl<UserMapper, User> implements UserService {

}
~~~
~~~java
/**
 * Controller引用
 */
@Controller
@RequestMapping("/user")
public class UserAction {

    @Autowired
    private UserService userService;

}
~~~
