### ISSUE TITLE
表无法显示，报了一个错误

### ISSUE THREAD

**Issue by oweson** [davidfantasy/mybatis-plus-generator-ui#31]
异常信息如下：  数据库mysql

Caused by: java.lang.NoSuchFieldError: KINGBASE_ES
	at com.baomidou.mybatisplus.generator.config.querys.DbQueryRegistry.<init>(DbQueryRegistry.java:42)
	at com.baomidou.mybatisplus.generator.config.DataSourceConfig.getDbQuery(DataSourceConfig.java:83)
	at com.github.davidfantasy.mybatisplus.generatorui.service.DatabaseService.getTablesFromDb(DatabaseService.java:27)
	at com.github.davidfantasy.mybatisplus.generatorui.controller.DatabaseController.getAllTables(DatabaseController.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:892)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1039)
	... 40 common frames omitted

**Comment by davidfantasy** [comment]
应该是你项目中引入的mybatis-plus版本不匹配造成的，把你项目的POM贴出来看看
