### ISSUE TITLE
未正常运行

### ISSUE THREAD

**Issue by zhuanqizhirou** [davidfantasy/mybatis-plus-generator-ui#34]
### 当前使用版本(必填,否则不予处理)
1.3.4
### 该问题是如何引起的？(确定最新版也有问题再提!!!)
所有的代码变更如图：在GeneratorUIServer.java中右键运行mian就报错
![image](https://user-images.githubusercontent.com/4990547/102069783-31883480-3e39-11eb-881a-dab1549252ce.png)

### 报错信息
`
Exception in thread "main" java.lang.NoSuchMethodError: 'void org.springframework.boot.builder.SpringApplicationBuilder.<init>(java.lang.Class[])'
	at com.github.davidfantasy.mybatisplus.generatorui.MybatisPlusToolsApplication.run(MybatisPlusToolsApplication.java:46)
	at com.xxx.GeneratorUIServer.main(GeneratorUIServer.java:49)

Process finished with exit code 1

`

**Comment by zhuanqizhirou** [comment]
可能spring boot版本一个1.5.9 一个2.+导致

**Comment by zhuanqizhirou** [comment]
springboot版本问题
