### ISSUE TITLE
源码(前端)运行报错

### ISSUE THREAD

**Issue by yqingf** [davidfantasy/mybatis-plus-generator-ui#44]
### 报错信息
```
ERROR in ./.nuxt/client.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: /Users/wangwenwu/source/java/mybatis-plus-generator-ui/src/frontend/.nuxt/client.js: Cannot find module '@babel/preset-env/lib/utils'
Require stack:
- /Users/wangwenwu/source/java/mybatis-plus-generator-ui/src/frontend/node_modules/@nuxt/babel-preset-app/src/polyfills-plugin.js
- /Users/wangwenwu/source/java/mybatis-plus-generator-ui/src/frontend/node_modules/@nuxt/babel-preset-app/src/index.js
- /Users/wangwenwu/source/java/mybatis-plus-generator-ui/src/frontend/node_modules/@babel/core/lib/config/files/module-types.js
- /Users/wangwenwu/source/java/mybatis-plus-generator-ui/src/frontend/node_modules/@babel/core/lib/config/files/configuration.js
- /Users/wangwenwu/source/java/mybatis-plus-generator-ui/src/frontend/node_modules/@babel/core/lib/config/files/index.js
- /Users/wangwenwu/source/java/mybatis-plus-generator-ui/src/frontend/node_modules/@babel/core/lib/index.js
- /Users/wangwenwu/source/java/mybatis-plus-generator-ui/src/frontend/node_modules/babel-loader/lib/index.js
- /Users/wangwenwu/source/java/mybatis-plus-generator-ui/src/frontend/node_modules/loader-runner/lib/loadLoader.js
- /Users/wangwenwu/source/java/mybatis-plus-generator-ui/src/frontend/node_modules/loader-runner/lib/LoaderRunner.js
- /Users/wangwenwu/source/java/mybatis-plus-generator-ui/src/frontend/node_modules/webpack/lib/NormalModule.js
- /Users/wangwenwu/source/java/mybatis-plus-generator-ui/src/frontend/node_modules/webpack/lib/NormalModuleFactory.js
- /Users/wangwenwu/source/java/mybatis-plus-generator-ui/src/frontend/node_modules/webpack/lib/Compiler.js
- /Users/wangwenwu/source/java/mybatis-plus-generator-ui/src/frontend/node_modules/webpack/lib/webpack.js
- /Users/wangwenwu/source/java/mybatis-plus-generator-ui/src/frontend/node_modules/@nuxt/webpack/dist/webpack.js
- /Users/wangwenwu/source/java/mybatis-plus-generator-ui/src/frontend/node_modules/@nuxt/cli/dist/cli-command.js
- /Users/wangwenwu/source/java/mybatis-plus-generator-ui/src/frontend/node_modules/@nuxt/cli/dist/cli.js
- /Users/wangwenwu/source/java/mybatis-plus-generator-ui/src/frontend/node_modules/nuxt/bin/nuxt.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at PluginPass.Program (/Users/wangwenwu/source/java/mybatis-plus-generator-ui/src/frontend/node_modules/@nuxt/babel-preset-app/src/polyfills-plugin.js:15:34)
    at newFn (/Users/wangwenwu/source/java/mybatis-plus-generator-ui/src/frontend/node_modules/@babel/traverse/lib/visitors.js:171:21)
    at NodePath._call (/Users/wangwenwu/source/java/mybatis-plus-generator-ui/src/frontend/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/Users/wangwenwu/source/java/mybatis-plus-generator-ui/src/frontend/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/Users/wangwenwu/source/java/mybatis-plus-generator-ui/src/frontend/node_modules/@babel/traverse/lib/path/context.js:90:31)
    at TraversalContext.visitQueue (/Users/wangwenwu/source/java/mybatis-plus-generator-ui/src/frontend/node_modules/@babel/traverse/lib/context.js:99:16)
    at TraversalContext.visitSingle (/Users/wangwenwu/source/java/mybatis-plus-generator-ui/src/frontend/node_modules/@babel/traverse/lib/context.js:73:19)
    at TraversalContext.visit (/Users/wangwenwu/source/java/mybatis-plus-generator-ui/src/frontend/node_modules/@babel/traverse/lib/context.js:127:19)
    at Function.traverse.node (/Users/wangwenwu/source/java/mybatis-plus-generator-ui/src/frontend/node_modules/@babel/traverse/lib/index.js:76:17)
    at traverse (/Users/wangwenwu/source/java/mybatis-plus-generator-ui/src/frontend/node_modules/@babel/traverse/lib/index.js:56:12)
    at transformFile (/Users/wangwenwu/source/java/mybatis-plus-generator-ui/src/frontend/node_modules/@babel/core/lib/transformation/index.js:105:29)
    at transformFile.next (<anonymous>)
 @ multi ./.nuxt/client.js app[0]

 FATAL  Nuxt build error

  at WebpackBundler.webpackCompile (node_modules/@nuxt/webpack/dist/webpack.js:5326:21)
  at processTicksAndRejections (internal/process/task_queues.js:95:5)
  at async WebpackBundler.build (node_modules/@nuxt/webpack/dist/webpack.js:5275:5)
  at async Builder.build (node_modules/@nuxt/builder/dist/builder.js:5598:5)
  at async Generator.initiate (node_modules/@nuxt/generator/dist/generator.js:70:7)
  at async Generator.generate (node_modules/@nuxt/generator/dist/generator.js:40:5)
  at async Object.run (node_modules/@nuxt/cli/dist/cli-build.js:96:7)
  at async NuxtCommand.run (node_modules/@nuxt/cli/dist/cli-command.js:2575:7)


   ╭─────────────────────────────╮
   │                             │
   │   ✖ Nuxt Fatal Error        │
   │                             │
   │   Error: Nuxt build error   │
   │                             │
   ╰─────────────────────────────╯


    at ChildProcess.exithandler (child_process.js:319:12)
    at ChildProcess.emit (events.js:376:20)
    at maybeClose (internal/child_process.js:1055:16)
    at Socket.<anonymous> (internal/child_process.js:441:11)
    at Socket.emit (events.js:376:20)
    at Pipe.<anonymous> (net.js:673:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'nuxt build'
}
```

**Comment by davidfantasy** [comment]
清空node_modules，然后重新install

**Comment by hdtopku** [comment]
试试
```shell
npm i @babel/preset-env@7.12.17
```
