### ISSUE TITLE
访问首页报错GAUSS

### ISSUE THREAD

**Issue by Dustin015** [davidfantasy/mybatis-plus-generator-ui#76]
### 当前使用版本(必填,否则不予处理)
1.4.5
### 该问题是如何引起的？(确定最新版也有问题再提!!!)
启动成功，访问http://127.0.0.1:8068 ,然后报错。
![image](https://user-images.githubusercontent.com/17263991/228474900-b1ab3943-acf0-4713-843d-689f05ee574b.png)

### 报错信息
Caused by: java.lang.NoSuchFieldError: GAUSS
	at com.baomidou.mybatisplus.generator.config.querys.DbQueryRegistry.<init>(DbQueryRegistry.java:44)
	at com.baomidou.mybatisplus.generator.config.DataSourceConfig.getDbQuery(DataSourceConfig.java:83)
	at com.github.davidfantasy.mybatisplus.generatorui.service.DatabaseService.getTablesFromDb(DatabaseService.java:27)
	at com.github.davidfantasy.mybatisplus.generatorui.controller.DatabaseController.getAllTables(DatabaseController.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:888)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	... 36 common frames omitted

**Comment by davidfantasy** [comment]
依赖版本冲突导致的，你需要引入与mybatis-plus版本相对应的mybatis-plus-generator-ui，1.4.5版本支持的mybatis-plus版本是3.4.x
