### ISSUE TITLE
拉取代码运行 生成代码报错

### ISSUE THREAD

**Issue by Circlefork** [davidfantasy/mybatis-plus-generator-ui#80]
Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: com/baomidou/mybatisplus/extension/activerecord/Model
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1086) ~[spring-webmvc-5.3.25.jar:5.3.25]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:964) ~[spring-webmvc-5.3.25.jar:5.3.25]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) [spring-webmvc-5.3.25.jar:5.3.25]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) [spring-webmvc-5.3.25.jar:5.3.25]
找不到mybatisplus的类 但是依赖没有问题

**Comment by Circlefork** [comment]
已解决 需要自己加mybatis-plus依赖
